name = "rootd-waitlist-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Custom domain configuration for rootd.app
# We'll set up the custom domain after deployment

# Environment variables (secrets will be set via wrangler secret put)
[vars]
GOOGLE_SHEETS_SHEET_ID = "188OusdEm-ByfeRTwQAfcNnIDsPmIzvStzIxMlbsGJaQ"

# Secrets (set these via: wrangler secret put SECRET_NAME)
# GOOGLE_SHEETS_CLIENT_EMAIL
# GOOGLE_SHEETS_PRIVATE_KEY
